---
title: "Lab10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages(c("RSQLite", "DBI"))

library(RSQLite)
library(DBI)

# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)
```

Are the table there?

```{r}
dbListTables(con)
```

You can also use knitr +SQL !

```{sql, connection=con, output.var="x1"}
PRAGMA table_info(actor)
```

```{r}
x1
```

This is equivalent to use `dbGetQuery`
```{r}
dbGetQuery(con, "PRAGMA table_info(actor)")
```

## Question 1

AND using the LIMIT clause (`head()` in R) to just show the first 5

```{r}
dbGetQuery(con, "
/*This is COMMENT!*/
SELECT actor_id, first_name, last_name
FROM actor /* you can add comments
using mutiple lines*/
ORDER by last_name, first_name
LIMIT 5")
```

## Question 2

```{r}
dbGetQuery(con, "
SELECT actor_id, first_name, last_name
FROM actor 
WHERE last_name IN ('WILLIAMS', 'DAVIS')")
```


## Question 3

```{r}
dbGetQuery(con, "PRAGMA table_info(rental)")
```

```{r}
dbGetQuery(con, "
SELECT DISTINCT customer_id
FROM rental 
WHERE date(rental_date) = '2005-07-05'
LIMIT 5")
```

## Question 4

## 4.1

```{r}
dbGetQuery(con, "PRAGMA table_info(payment)")
```

```{r}
q <- dbSendQuery(con, "
SELECT *
FROM payment
WHERE amount IN (1.99, 7.99, 9.99)")
dbFetch(q, n = 10)
dbFetch(q, n = 10)
dbClearResult(q)
```

## 4.2

```{r}
dbGetQuery(con, "
SELECT *
FROM payment 
WHERE amount > 5
LIMIT 5")
```

Count how many are

```{r}
dbGetQuery(con, "
SELECT COUNT(*)
FROM payment 
WHERE amount > 5
")
```

Counting per `staff_id`

```{r}
dbGetQuery(con, "
SELECT staff_id, COUNT(*) AS N
FROM payment
/* GROUP BY goes after WHERE*/
WHERE amount > 5
GROUP BY staff_id")
```

## Question 5

```{r}
dbGetQuery(con, "
SELECT p.payment_id, p.amount
FROM payment AS p
  INNER JOIN customer AS c ON p.customer_id = c.customer_id
WHERE c.last_name = 'DAVIS'")
```

## Question 6

## 6.1

```{r}
dbGetQuery(con, "
SELECT COUNT(*)
FROM rental
")
```

## 6.2

```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS 'N Rentals'
FROM rental
GROUP BY customer_id
LIMIT 5")
```

## 6.3

```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS 'N Rentals'
FROM rental
GROUP BY customer_id 
/* this is equivalent to -`N Rentals` */
ORDER BY `N Rentals` DESC
LIMIT 5")
```

## 6.4

```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS 'N Rentals'
FROM rental
GROUP BY customer_id 
HAVING `N Rentals` >= 40
ORDER BY `N Rentals`
LIMIT 5")
```

## Question 7

```{r}
dbGetQuery(con, "
SELECT 
    MAX(amount) AS `max`,
    MIN(amount) AS `min`,
    AVG(amount) AS `avg`,
    SUM(amount) AS `sum`
    FROM payment
")
```

## 7.1

```{r}
dbGetQuery(con, "
SELECT
    customer_id,
    MAX(amount) AS `max`,
    MIN(amount) AS `min`,
    AVG(amount) AS `avg`,
    SUM(amount) AS `sum`
    FROM payment
    GROUP BY customer_id
    LIMIT 5")
```

## 7.2

```{r}
dbGetQuery(con, "
SELECT 
    customer_id,
    MAX(amount) AS `max`,
    MIN(amount) AS `min`,
    AVG(amount) AS `avg`,
    SUM(amount) AS `sum`
    FROM payment
    GROUP BY customer_id
    HAVING COUNT(*) > 5
    LIMIT 5
")
```

```{r cleaning}
dbDisconnect(con)
```









