---
title: "Lab07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(xml2)
library(stringr)
library(tidytext)
```

## Q1

```{r}
# Downloading the website
website <- xml2::read_html("https://pubmed.ncbi.nlm.nih.gov/?term=sars-cov-2")

# Finding the counts
counts <- xml2::xml_find_first(website, "/html/body/main/div[9]/div[2]/div[2]/div[1]/span")

# Turning it into text
counts <- as.character(counts)

# Extracting the data using regex
stringr::str_extract(counts, "[0-9,]+")
# Extracting the data using regex alternatively
stringr::str_extract(counts, "[[:digit:],]+")
```

## Q2

```{r hawaii}
library(httr)
query_ids <- GET(
  url   = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi",
  query = list(
    db     = "pubmed",
    term   = "covid19 hawaii",
    retmax = 1000)
)

# Extracting the content of the response of GET
ids <- httr::content(query_ids)
ids
```

## Q3

```{r}
# Turn the result into a character vector
ids <- as.character(ids)

# Find all the ids 
ids <- stringr::str_extract_all(ids, "<Id>[[:digit:]]+</Id>")[[1]]

# Remove all the leading and trailing <Id> </Id>. Make use of "|"
ids <- stringr::str_remove_all(ids, "<Id>|</Id>")
# Remove all the leading and trailing <Id> </Id>. Make use of "|" alternatively
stringr::str_remove_all(ids, "</?Id>")

head(ids)

```

```{r}
publications <- GET(
  url   = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi",
  query = list(
    db      = "pubmed",
    id      = I(paste(ids, collapse = ",")),
    retmax  = 1000,
    rettype = "abstract"
    )
)

# Turning the output into character vector
publications <- httr::content(publications)
publications_txt <- as.character(publications)
```

## Q4

```{r univ-insti}
institution <- str_extract_all(
  tolower(publications_txt),
  "university\\s+of\\s+[[:alpha:]-]+|[[:alpha:]-]+\\s+institute\\s+of\\s+[[:alpha:]-]+"
  ) 
institution <- unlist(institution)
table(institution)
```

```{r sch-dep}
schools_and_deps <- str_extract_all(
  tolower(abstracts_txt),
  "school\\s+of\\s+[[:alpha:]-]+|[[:alpha:]-]+\\s+department\\s+of\\s+[[:alpha:]-]+"
  )
table(schools_and_deps)
```

## Q5

```{r}
pub_char_list <- xml2::xml_children(publications)
pub_char_list <- sapply(pub_char_list, as.character)
```

```{r}
abstracts <- str_extract(pub_char_list, "<Abstract>[[:print:][:space:]]</Abstract>")
abstracts <- str_remove_all(abstracts, "</?[[:alnum:]- =\"]+>")
abstracts <- str_replace_all(abstracts, "[:space:]+", " ")
```

```{r}
titles <- str_extract(pub_char_list, "<ArticleTitle>[[:print:][:space:]+</ArticleTitle>]")
titles <- str_remove_all(titles, "")
```


```{r}
database <- data.frame(
  PubMedID = ids,
  Title = titles,
  Abstract = abstracts
)
knitr::kable(database)
```






















